#!/bin/bash
set -exu

git fetch -p

# check rebase
hash1=$(git show-ref -s origin/master)
hash2=$(git merge-base origin/master HEAD)
if [ "${hash1}" = "${hash2}" ] ; then
    echo "no rebase is needed"
else
    echo "Rebase is required"
    exit 1
fi

# update
p4 sync


# make change
p5 reset
git reset --hard
git clean -ffdx
p4 reconcile -eda
p4 change -o
